package com.kaen.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysFile<M extends BaseSysFile<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setPath(java.lang.String path) {
		set("path", path);
		return (M)this;
	}
	
	public java.lang.String getPath() {
		return getStr("path");
	}

	public M setUploadTime(java.util.Date uploadTime) {
		set("upload_time", uploadTime);
		return (M)this;
	}
	
	public java.util.Date getUploadTime() {
		return getDate("upload_time");
	}

	public M setSort(java.lang.Long sort) {
		set("sort", sort);
		return (M)this;
	}
	
	public java.lang.Long getSort() {
		return getLong("sort");
	}

	public M setDel(java.lang.String del) {
		set("del", del);
		return (M)this;
	}
	
	public java.lang.String getDel() {
		return getStr("del");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

	public M setCreateUserCode(java.lang.String createUserCode) {
		set("create_user_code", createUserCode);
		return (M)this;
	}
	
	public java.lang.String getCreateUserCode() {
		return getStr("create_user_code");
	}

	public M setCreateUserName(java.lang.String createUserName) {
		set("create_user_name", createUserName);
		return (M)this;
	}
	
	public java.lang.String getCreateUserName() {
		return getStr("create_user_name");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}

	public M setUpdateUserCode(java.lang.String updateUserCode) {
		set("update_user_code", updateUserCode);
		return (M)this;
	}
	
	public java.lang.String getUpdateUserCode() {
		return getStr("update_user_code");
	}

	public M setUpdateUserName(java.lang.String updateUserName) {
		set("update_user_name", updateUserName);
		return (M)this;
	}
	
	public java.lang.String getUpdateUserName() {
		return getStr("update_user_name");
	}

	public M setSuffix(java.lang.String suffix) {
		set("suffix", suffix);
		return (M)this;
	}
	
	public java.lang.String getSuffix() {
		return getStr("suffix");
	}

	public M setFromId(java.lang.String fromId) {
		set("from_id", fromId);
		return (M)this;
	}
	
	public java.lang.String getFromId() {
		return getStr("from_id");
	}

	public M setFromTable(java.lang.String fromTable) {
		set("from_table", fromTable);
		return (M)this;
	}
	
	public java.lang.String getFromTable() {
		return getStr("from_table");
	}

}

