package com.kaen.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysDict<M extends BaseSysDict<M>> extends Model<M> implements IBean {

	public M setDictId(java.lang.String dictId) {
		set("dict_id", dictId);
		return (M)this;
	}
	
	public java.lang.String getDictId() {
		return getStr("dict_id");
	}

	public M setDictValue(java.lang.String dictValue) {
		set("dict_value", dictValue);
		return (M)this;
	}
	
	public java.lang.String getDictValue() {
		return getStr("dict_value");
	}

	public M setDictName(java.lang.String dictName) {
		set("dict_name", dictName);
		return (M)this;
	}
	
	public java.lang.String getDictName() {
		return getStr("dict_name");
	}

	public M setDictType(java.lang.String dictType) {
		set("dict_type", dictType);
		return (M)this;
	}
	
	public java.lang.String getDictType() {
		return getStr("dict_type");
	}

	public M setDictRemarks(java.lang.String dictRemarks) {
		set("dict_remarks", dictRemarks);
		return (M)this;
	}
	
	public java.lang.String getDictRemarks() {
		return getStr("dict_remarks");
	}

	public M setDictCName(java.lang.String dictCName) {
		set("dict_c_name", dictCName);
		return (M)this;
	}
	
	public java.lang.String getDictCName() {
		return getStr("dict_c_name");
	}

	public M setDictCssStyle(java.lang.String dictCssStyle) {
		set("dict_css_style", dictCssStyle);
		return (M)this;
	}
	
	public java.lang.String getDictCssStyle() {
		return getStr("dict_css_style");
	}

	public M setDictSort(java.lang.Integer dictSort) {
		set("dict_sort", dictSort);
		return (M)this;
	}
	
	public java.lang.Integer getDictSort() {
		return getInt("dict_sort");
	}

	public M setDel(java.lang.String del) {
		set("del", del);
		return (M)this;
	}
	
	public java.lang.String getDel() {
		return getStr("del");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

	public M setCreateUserCode(java.lang.String createUserCode) {
		set("create_user_code", createUserCode);
		return (M)this;
	}
	
	public java.lang.String getCreateUserCode() {
		return getStr("create_user_code");
	}

	public M setCreateUserName(java.lang.String createUserName) {
		set("create_user_name", createUserName);
		return (M)this;
	}
	
	public java.lang.String getCreateUserName() {
		return getStr("create_user_name");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}

	public M setUpdateUserCode(java.lang.String updateUserCode) {
		set("update_user_code", updateUserCode);
		return (M)this;
	}
	
	public java.lang.String getUpdateUserCode() {
		return getStr("update_user_code");
	}

	public M setUpdateUserName(java.lang.String updateUserName) {
		set("update_user_name", updateUserName);
		return (M)this;
	}
	
	public java.lang.String getUpdateUserName() {
		return getStr("update_user_name");
	}

}

