package com.kaen.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setUserName(java.lang.String userName) {
		set("user_name", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setPwdErrCount(java.lang.Integer pwdErrCount) {
		set("pwd_err_count", pwdErrCount);
		return (M)this;
	}
	
	public java.lang.Integer getPwdErrCount() {
		return getInt("pwd_err_count");
	}

	public M setDel(java.lang.String del) {
		set("del", del);
		return (M)this;
	}
	
	public java.lang.String getDel() {
		return getStr("del");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

	public M setCreateUserCode(java.lang.String createUserCode) {
		set("create_user_code", createUserCode);
		return (M)this;
	}
	
	public java.lang.String getCreateUserCode() {
		return getStr("create_user_code");
	}

	public M setCreateUserName(java.lang.String createUserName) {
		set("create_user_name", createUserName);
		return (M)this;
	}
	
	public java.lang.String getCreateUserName() {
		return getStr("create_user_name");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}

	public M setUpdateUserCode(java.lang.String updateUserCode) {
		set("update_user_code", updateUserCode);
		return (M)this;
	}
	
	public java.lang.String getUpdateUserCode() {
		return getStr("update_user_code");
	}

	public M setUpdateUserName(java.lang.String updateUserName) {
		set("update_user_name", updateUserName);
		return (M)this;
	}
	
	public java.lang.String getUpdateUserName() {
		return getStr("update_user_name");
	}

}

