package com.kaen.entity;

import java.io.Serializable;

import com.kaen.entity.base.BaseSysFile;

/** 实体类
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysFile extends BaseSysFile<SysFile> implements Serializable{
	public static final String TABLE_NAME = "sys_file";
	public static final String PRIMARY_KEY = "id";
	public static final String SOFT_DEL_FIELD= "";
	
	public static final SysFile dao = new SysFile().dao();
}

