package com.kaen.entity;

import java.io.Serializable;

import com.kaen.entity.base.BaseSysUser;

/** 实体类
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUser extends BaseSysUser<SysUser> implements Serializable{
	public static final String TABLE_NAME = "sys_user";
	public static final String PRIMARY_KEY = "id";
	public static final String SOFT_DEL_FIELD= "";
	
	public static final SysUser dao = new SysUser().dao();
}

